/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cz_romario_opensudoku_gui_GeneratorLib */

#ifndef _Included_cz_romario_opensudoku_gui_GeneratorLib
#define _Included_cz_romario_opensudoku_gui_GeneratorLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cz_romario_opensudoku_gui_GeneratorLib
 * Method:    generateSudoku
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_cz_romario_opensudoku_gui_GeneratorLib_generateSudoku
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
