/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_umaine_opensudoku_generator_GeneratorLib */

#ifndef _Included_edu_umaine_opensudoku_generator_GeneratorLib
#define _Included_edu_umaine_opensudoku_generator_GeneratorLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_umaine_opensudoku_generator_GeneratorLib
 * Method:    generateSudoku
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_edu_umaine_opensudoku_generator_GeneratorLib_generateSudoku
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
